import { Theme, themePropDefs } from '@radix-ui/themes';
import type { Metadata } from 'next'
import { ThemeProvider } from 'next-themes';
import { Inter } from 'next/font/google'
import '@radix-ui/themes/styles.css';
import './globals.css'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return <html>
    <body>
    <ThemeProvider attribute="class">
        <Theme accentColor={'gold'} scaling="105%" style={{height: "100%"}}>
            {children}
        </Theme>
    </ThemeProvider>
    </body>
    </html>
}
